from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)


legacy_metadata = MetaData()

jobs = Table(
    "jobs",
    legacy_metadata,
    Column("id", String(64), primary_key=True),
    Column("name", String(255), nullable=False, default=""),
    Column("mode", String(16), nullable=False, default="cross"),
    Column("pipeline_version", String(32), nullable=False, default="event_cluster_v2"),
    Column("match_preset", String(16), nullable=False, default="balanced"),
    Column("time_window_days", Integer, nullable=False, default=0),
    Column("status", String(32), nullable=False, default="queued"),
    Column("stage", String(32), nullable=False, default="queued"),
    Column("total_records", Integer, nullable=False, default=0),
    Column("extracted_records", Integer, nullable=False, default=0),
    Column("candidate_count", Integer, nullable=False, default=0),
    Column("judged_count", Integer, nullable=False, default=0),
    Column("extraction_failure_count", Integer, nullable=False, default=0),
    Column("judgement_failure_count", Integer, nullable=False, default=0),
    Column("retry_count", Integer, nullable=False, default=0),
    Column("inflight_batches", Integer, nullable=False, default=0),
    Column("pause_requested", Boolean, nullable=False, default=False),
    Column("lease_owner", String(128)),
    Column("lease_expires_at", DateTime(timezone=True)),
    Column("heartbeat_at", DateTime(timezone=True)),
    Column("error_message", Text),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

records = Table(
    "records",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("source", String(1), nullable=False),
    Column("source_row", Integer, nullable=False),
    Column("work_order_id", String(255)),
    Column("received_at", String(64)),
    Column("title", Text),
    Column("category", Text),
    Column("category_level_1", Text),
    Column("category_level_2", Text),
    Column("category_level_3", Text),
    Column("category_level_4", Text),
    Column("normalized_title", Text),
    Column("event_signature", Text),
    Column("normalized_location", Text),
    Column("appeal_text", Text),
    Column("region", String(255)),
    Column("street", String(255)),
    Column("phone_hash", String(64)),
    Column("raw_json", JSON, nullable=False, default=dict),
    Column("extraction_status", String(32), nullable=False, default="pending"),
    Column("extraction_json", JSON),
    Column("embedding_status", String(32), nullable=False, default="pending"),
    UniqueConstraint("job_id", "source", "source_row", name="uq_records_source_row"),
)

candidate_pairs = Table(
    "candidate_pairs",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("record_a_id", Integer, ForeignKey("records.id", ondelete="CASCADE"), nullable=False),
    Column("record_b_id", Integer, ForeignKey("records.id", ondelete="CASCADE"), nullable=False),
    Column("recall_reasons", JSON, nullable=False, default=list),
    Column("vector_score", Float),
    Column("rerank_score", Float),
    Column("rule_status", String(32), nullable=False, default="candidate"),
    Column("judgement_status", String(32), nullable=False, default="pending"),
    Column("llm_decision", String(32)),
    Column("confidence", Float),
    Column("evidence_json", JSON),
    Column("hard_conflicts_json", JSON),
    Column("event_name_suggestion", Text),
    UniqueConstraint("job_id", "record_a_id", "record_b_id", name="uq_candidate_pair"),
)

reviews = Table(
    "reviews",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("candidate_pair_id", Integer, ForeignKey("candidate_pairs.id", ondelete="CASCADE"), nullable=False, unique=True),
    Column("decision", String(32), nullable=False),
    Column("note", Text),
    Column("reviewed_at", DateTime(timezone=True), nullable=False),
)

event_groups = Table(
    "event_groups",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("region", String(255)),
    Column("first_received_at", String(64)),
    Column("last_received_at", String(64)),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

event_members = Table(
    "event_members",
    legacy_metadata,
    Column("event_group_id", Integer, ForeignKey("event_groups.id", ondelete="CASCADE"), primary_key=True),
    Column("record_id", Integer, ForeignKey("records.id", ondelete="CASCADE"), primary_key=True),
)

candidate_events = Table(
    "candidate_events",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("name", Text, nullable=False),
    Column("status", String(32), nullable=False, default="review"),
    Column("confidence", Float),
    Column("evidence_json", JSON),
    Column("region", String(255)),
    Column("street", String(255)),
    Column("category_level_1", Text),
    Column("category_level_2", Text),
    Column("category_level_3", Text),
    Column("category_level_4", Text),
    Column("final_event_group_id", Integer, ForeignKey("event_groups.id", ondelete="SET NULL")),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
)

candidate_event_members = Table(
    "candidate_event_members",
    legacy_metadata,
    Column("candidate_event_id", Integer, ForeignKey("candidate_events.id", ondelete="CASCADE"), primary_key=True),
    Column("record_id", Integer, ForeignKey("records.id", ondelete="CASCADE"), primary_key=True, unique=True),
    Column("confidence", Float),
    Column("role", String(32), nullable=False, default="member"),
    Column("assignment_source", String(32), nullable=False, default="model"),
)

event_review_actions = Table(
    "event_review_actions",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("candidate_event_id", Integer, ForeignKey("candidate_events.id", ondelete="SET NULL")),
    Column("action", String(32), nullable=False),
    Column("note", Text),
    Column("details_json", JSON),
    Column("created_at", DateTime(timezone=True), nullable=False),
)

job_batches = Table(
    "job_batches",
    legacy_metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("job_id", String(64), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False),
    Column("stage", String(32), nullable=False),
    Column("batch_index", Integer, nullable=False),
    Column("status", String(32), nullable=False, default="pending"),
    Column("attempts", Integer, nullable=False, default=0),
    Column("item_ids", JSON, nullable=False, default=list),
    Column("error_message", Text),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("job_id", "stage", "batch_index", name="uq_job_stage_batch"),
)
